export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const UPDATE_OPTION_ID = 'UPDATE_OPTION_ID';
export const UPDATE_DISCOUNT_PRICE = 'UPDATE_DISCOUNT_PRICE';
